name: DockerCI 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout la branche
        uses: actions/checkout@v4

      - name: Login sur le Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build et push l image API du TP1 
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/api
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/carpart_tp:api-latest

      - name: Build et push l image BDD du TP1 
        uses: docker/build-push-action@v6
        with:
          context: ./TP1/bdd
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/carpart_tp:bdd-latest

      - name: Build et push l image BDD du TP1 
        uses: docker/build-push-action@v6
        with:
          context: ./TP2
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/carpart_tp:tp2-latest     
